### ISSUE TITLE
bitmap_allocator.h:200:7: internal compiler error: Segmentation fault

### ISSUE THREAD

**Issue by kingzhe2011** [ps3dev/ps3toolchain#65]
In file included from ../../../../../libstdc++-v3/src/c++98/bitmap_allocator.cc:26:0:
/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/powerpc64-ps3-elf/libstdc++-v3/include/ext/bitmap_allocator.h: In member function 'void __gnu_cxx::__detail::__mini_vector<_Tp>::insert(__gnu_cxx::__detail::__mini_vector<_Tp>::iterator, __gnu_cxx::__detail::__mini_vector<_Tp>::const_reference) [with _Tp = std::pair<__gnu_cxx::bitmap_allocator<char>::_Alloc_block*, __gnu_cxx::bitmap_allocator<char>::_Alloc_block*>; __gnu_cxx::__detail::__mini_vector<_Tp>::iterator = std::pair<__gnu_cxx::bitmap_allocator<char>::_Alloc_block*, __gnu_cxx::bitmap_allocator<char>::_Alloc_block*>*; __gnu_cxx::__detail::__mini_vector<_Tp>::const_reference = const std::pair<__gnu_cxx::bitmap_allocator<char>::_Alloc_block*, __gnu_cxx::bitmap_allocator<char>::_Alloc_block*>&]':
/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/powerpc64-ps3-elf/libstdc++-v3/include/ext/bitmap_allocator.h:200:7: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
/bin/bash ../../libtool --tag CXX --tag disable-shared  --mode=compile /home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/./gcc/xgcc -shared-libgcc -B/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/./gcc -nostdinc++ -L/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/powerpc64-ps3-elf/libstdc++-v3/src -L/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/powerpc64-ps3-elf/libstdc++-v3/src/.libs -nostdinc -B/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/powerpc64-ps3-elf/newlib/ -isystem /home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/powerpc64-ps3-elf/newlib/targ-include -isystem /home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/newlib/libc/include -B/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/powerpc64-ps3-elf/libgloss/rs6000 -L/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/powerpc64-ps3-elf/libgloss/libnosys -L/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/libgloss/rs6000 -B/ps3dev/ppu/powerpc64-ps3-elf/bin/ -B/ps3dev/ppu/powerpc64-ps3-elf/lib/ -isystem /ps3dev/ppu/powerpc64-ps3-elf/include -isystem /ps3dev/ppu/powerpc64-ps3-elf/sys-include    -I/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/libstdc++-v3/../libgcc -I/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/powerpc64-ps3-elf/libstdc++-v3/include/powerpc64-ps3-elf -I/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/powerpc64-ps3-elf/libstdc++-v3/include -I/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/libstdc++-v3/libsupc++   -fno-implicit-templates -Wall -Wextra -Wwrite-strings -Wcast-qual -Wabi  -fdiagnostics-show-location=once   -ffunction-sections -fdata-sections  -frandom-seed=compatibility-debug_list.lo -g -O2 -c -o compatibility-debug_list.lo ../../../../../libstdc++-v3/src/c++98/compatibility-debug_list.cc
make[5]: *** [bitmap_allocator.lo] Error 1
make[5]: *** Waiting for unfinished jobs....
libtool: compile:  /home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/./gcc/xgcc -shared-libgcc -B/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/./gcc -nostdinc++ -L/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/powerpc64-ps3-elf/libstdc++-v3/src -L/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/powerpc64-ps3-elf/libstdc++-v3/src/.libs -nostdinc -B/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/powerpc64-ps3-elf/newlib/ -isystem /home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/powerpc64-ps3-elf/newlib/targ-include -isystem /home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/newlib/libc/include -B/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/powerpc64-ps3-elf/libgloss/rs6000 -L/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/powerpc64-ps3-elf/libgloss/libnosys -L/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/libgloss/rs6000 -B/ps3dev/ppu/powerpc64-ps3-elf/bin/ -B/ps3dev/ppu/powerpc64-ps3-elf/lib/ -isystem /ps3dev/ppu/powerpc64-ps3-elf/include -isystem /ps3dev/ppu/powerpc64-ps3-elf/sys-include -I/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/libstdc++-v3/../libgcc -I/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/powerpc64-ps3-elf/libstdc++-v3/include/powerpc64-ps3-elf -I/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/powerpc64-ps3-elf/libstdc++-v3/include -I/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/libstdc++-v3/libsupc++ -fno-implicit-templates -Wall -Wextra -Wwrite-strings -Wcast-qual -Wabi -fdiagnostics-show-location=once -ffunction-sections -fdata-sections -frandom-seed=compatibility-debug_list.lo -g -O2 -c ../../../../../libstdc++-v3/src/c++98/compatibility-debug_list.cc -o compatibility-debug_list.o
make[5]: Leaving directory `/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/powerpc64-ps3-elf/libstdc++-v3/src/c++98'
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory `/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/powerpc64-ps3-elf/libstdc++-v3/src'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/powerpc64-ps3-elf/libstdc++-v3'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu/powerpc64-ps3-elf/libstdc++-v3'
make[1]: *** [all-target-libstdc++-v3] Error 2
make[1]: Leaving directory `/home/leevictor/ps3dev/ps3toolchain/build/gcc-4.7.0/build-ppu'
make: *** [all] Error 2

**Comment by zeldin** [comment]
Which version of gcc are you using on the build host?  I know that at least gcc-4.6.3 has an issue where building it with a newer gcc would cause a malfunctioning compiler.

**Comment by kingzhe2011** [comment]
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.3' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)

**Comment by zeldin** [comment]
Ok.  If you have access to a native 4.7 or 4.6 you could try compiling with that instead.  In the long run I think we should probably upgrade the toolchain to 4.7.4 (or a newer series) since 4.7.0 has a lot of bugs...

**Comment by zeldin** [comment]
I'm able to reproduce the issue on my system (native gcc = 4.9.3).

**Comment by zeldin** [comment]
I have now pushed an upgrade to gcc 4.7.4 (and an upgrade of gdb to 7.5.1, to get rid of a texinfo incompatibility).  With this everything builds cleanly on my system.  @kingzhe2011 If you could test if it works for you as well that would be great so that we can close the issue.  Thanks.

**Comment by kingzhe2011** [comment]
ok i will try

**Comment by kingzhe2011** [comment]
ok i got it thank you @zeldin thank you
