### ISSUE TITLE
creating fails on newlib

### ISSUE THREAD

**Issue by c0deisme** [ps3dev/ps3toolchain#69]
on Archlinux it fails to create the toolchain

gcc -c   -g -O2 -DIN_GCC -DCROSS_DIRECTORY_STRUCTURE  -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wmissing-format-attribute -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings -Wold-style-definition -Wc++-compat   -DHAVE_CONFIG_H -I. -I. -I../../gcc -I../../gcc/. -I../../gcc/../include -I../../gcc/../libcpp/include -I/media/homebrew/ps3/ps3toolchain/build/gcc-4.7.4/build-ppu/./gmp -I/media/homebrew/ps3/ps3toolchain/build/gcc-4.7.4/gmp -I/media/homebrew/ps3/ps3toolchain/build/gcc-4.7.4/build-ppu/./mpfr -I/media/homebrew/ps3/ps3toolchain/build/gcc-4.7.4/mpfr -I/media/homebrew/ps3/ps3toolchain/build/gcc-4.7.4/mpc/src  -I../../gcc/../libdecnumber -I../../gcc/../libdecnumber/dpd -I../libdecnumber    ../../gcc/errors.c -o errors.o
if [ xinfo = xinfo ]; then \
        makeinfo --split-size=5000000 --split-size=5000000 --no-split -I . -I ../../gcc/doc \
                -I ../../gcc/doc/include -o doc/cpp.info ../../gcc/doc/cpp.texi; \
fi
if [ xinfo = xinfo ]; then \
        makeinfo --split-size=5000000 --split-size=5000000 --no-split -I . -I ../../gcc/doc \
                -I ../../gcc/doc/include -o doc/gcc.info ../../gcc/doc/gcc.texi; \
fi
../../gcc/doc/gcc.texi:89: warning: @tex should only appear at the beginning of a line
../../gcc/doc/gcc.texi:209: no matching `@end tex'
../../gcc/doc/gcc.texi:209: no matching `@end multitable'
../../gcc/doc/gcc.texi:209: no matching `@end titlepage'
make[2]: *** [Makefile:4343: doc/gcc.info] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/media/homebrew/ps3/ps3toolchain/build/gcc-4.7.4/build-ppu/gcc'
make[1]: *** [Makefile:3858: all-gcc] Error 2
make[1]: Leaving directory '/media/homebrew/ps3/ps3toolchain/build/gcc-4.7.4/build-ppu'
make: *** [Makefile:873: all] Error 2
../scripts/002-gcc-newlib-PPU.sh: Failed.
ERROR: Could not run the toolchain script.

**Comment by ryu-highabusa** [comment]
So what was the solution?

**Comment by zeldin** [comment]
Upgrading ppu-gcc from 4.7.4 to 7.2.0, most likely.  Old gcc and new `makeinfo` tends to give you errors like that.
