### ISSUE TITLE
check-libelf and check-ncurses fail on recent macOS

### ISSUE THREAD

**Issue by IngwiePhoenix** [ps3dev/ps3toolchain#79]
Recently, actually since a while now, Apple does not put certain files into `/usr` anymore - for instance, the `ncurses.h` file is actually here: `/Applications/Xcode.app//Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/ncurses.h`. And when installing `libelf` through Homebrew (`brew`), then the corresponding `libelf.h` is actually located as `libelf/libelf.h`.

Symlinking the two above fixed this and let the toolchain script pass the checks. Might be notable to mention here.

The `libelf.h` check can be done by just looking one folder deeper, and the ncurses check can be done either by a try-compile, or by looking for `libncurses.dylib` instead, which actually IS located in `/usr/lib`.

**Comment by bucanero** [comment]
I was building the toolchain under macOS Mojave and had those issues with the lib path after installing with brew.

I proposed a fix for the dependency checks here:
https://github.com/ps3dev/ps3toolchain/pull/84

**Comment by bucanero** [comment]
Just in case, there's also a compiled macOS toolchain here:
https://github.com/bucanero/ps3toolchain/releases/tag/macos-latest-a5186b17
