### ISSUE TITLE
necessary libssl-dev

### ISSUE THREAD

**Issue by AZO234** [ps3dev/ps3toolchain#81]
It seems that libssl-dev package is necessary for building with Ubuntu.

**Comment by sinful-butterfly** [comment]
I can confirm that libssl-dev is necessary, I had the same issue as you :/

**Comment by bucanero** [comment]
if any Linux/Ubuntu user needs it, there's a compiled toolchain here:
https://github.com/bucanero/ps3toolchain/releases/tag/ubuntu-latest-a5186b17

**Comment by miigotu** [comment]
Fixed in docs
