### ISSUE TITLE
../scripts/002-gcc-newlib-PPU.sh: Failed.

### ISSUE THREAD

**Issue by Klairm** [ps3dev/ps3toolchain#83]
After compiling toolchain.sh, itshows this error:

Makefile:897: recipe for target 'all' failed
make: *** [all] Error 2
../scripts/002-gcc-newlib-PPU.sh: Failed.

**Comment by Klairm** [comment]
Solved that error installing build-essentials, now the error is:


Makefile:838: recipe for target 'all' failed
make: *** [all] Error 2
../scripts/001-binutils-PPU.sh: Failed.
ERROR: Could not run the toolchain script.

**Comment by zeldin** [comment]
Hi.
I'm afraid we can't tell what's going wrong from that snippet, the actual error would have appeared further up in the printouts...
What platform and OS are you building on?  Did you follow the instructions how to set up the build environment?

**Comment by Klairm** [comment]
I'm using Linux Mint 19.01, and yes i read the instructions

**Comment by zeldin** [comment]
Unless you show the actual error message (you can put the full output of the script to pastebin or suchlike and put a link here in case it is long) there's not much help I can give except to suggest that you try the Docker approach (https://github.com/ps3dev/ps3dev-docker) and see if that works for you.  I also have some prebuilt images if you want to try that: https://cloud.docker.com/repository/docker/zeldin/ps3dev-docker/general

**Comment by Klairm** [comment]
I tried the docker and this shows:

root@linuxmint-PC:/home/ivan/GitHub/PS3/ps3dev-docker# sudo docker build -t ps3dev-docker .
Sending build context to Docker daemon   80.9kB
Step 1/8 : FROM ubuntu:17.10
 ---> e211a66937c6
Step 2/8 : MAINTAINER Naomi Peori <naomi@peori.ca>
 ---> Using cache
 ---> f6cb6c615e8f
Step 3/8 : ENV PS3DEV /usr/local/ps3dev
 ---> Using cache
 ---> 1b9dd3e45499
Step 4/8 : ENV PSL1GHT ${PS3DEV}
 ---> Using cache
 ---> c040afa6026c
Step 5/8 : ENV PATH ${PATH}:${PS3DEV}/bin:${PS3DEV}/ppu/bin:${PS3DEV}/spu/bin
 ---> Using cache
 ---> 283539d80194
Step 6/8 : RUN   apt-get -y update &&   apt-get -y install autoconf bison build-essential flex git libelf-dev libgmp3-dev libncurses5-dev libssl-dev libtool-bin pkg-config python-dev texinfo wget zlib1g-dev &&   apt-get -y clean autoclean autoremove &&   rm -rf /var/lib/{apt,dpkg,cache,log}/
 ---> Running in ab7519e02504
Ign:1 http://archive.ubuntu.com/ubuntu artful InRelease
Ign:2 http://archive.ubuntu.com/ubuntu artful-updates InRelease
Ign:3 http://archive.ubuntu.com/ubuntu artful-backports InRelease
Err:4 http://archive.ubuntu.com/ubuntu artful Release
  404  Not Found [IP: 91.189.88.152 80]
Err:5 http://archive.ubuntu.com/ubuntu artful-updates Release
  404  Not Found [IP: 91.189.88.152 80]
Err:6 http://archive.ubuntu.com/ubuntu artful-backports Release
  404  Not Found [IP: 91.189.88.152 80]
Ign:7 http://security.ubuntu.com/ubuntu artful-security InRelease
Err:8 http://security.ubuntu.com/ubuntu artful-security Release
  404  Not Found [IP: 91.189.91.26 80]
Reading package lists...
E: The repository 'http://archive.ubuntu.com/ubuntu artful Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu artful-updates Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu artful-backports Release' does not have a Release file.
E: The repository 'http://security.ubuntu.com/ubuntu artful-security Release' does not have a Release file.
The command '/bin/sh -c apt-get -y update &&   apt-get -y install autoconf bison build-essential flex git libelf-dev libgmp3-dev libncurses5-dev libssl-dev libtool-bin pkg-config python-dev texinfo wget zlib1g-dev &&   apt-get -y clean autoclean autoremove &&   rm -rf /var/lib/{apt,dpkg,cache,log}/' returned a non-zero code: 100

**Comment by zeldin** [comment]
Oh, marvelous.  It seems like Ubuntu has removed all the package files for Artful Aardvark.  This must have happened quite recently, it was working just a few weeks ago...
If you change `ubuntu:17.10` to `ubuntu:18.04` in the Dockerfile it should work again.  Sorry about that.

**Comment by Klairm** [comment]
Okay, now working but now:

sudo ./ps3dev-docker.sh make
make: *** No targets specified and no makefile found.  Stop

**Comment by zeldin** [comment]
Well, it's up to you to start developing a PS3 program now.  :smile:

**Comment by Klairm** [comment]
So now i can just compile the SDK right?

**Comment by zeldin** [comment]
You already have the ps3sdk in the docker image.  Or are you referring to some other SDK?
You can run any ps3sdk command, such as `ppu-gcc`, by prefixing it with `ps3dev-docker.sh`.
If you write a `Makefile` for your program you can just run `ppu-gcc` directly in the `Makefile` and prefix the `make` command with `ps3dev-docker.sh`.

**Comment by Klairm** [comment]
Oh okay I'm just stupid haha

Thanks, now I can test my skills on other system! :)
