### ISSUE TITLE
Problems using Debian on WSL

### ISSUE THREAD

**Issue by nandolawson** [ps3dev/ps3toolchain#85]
I've tried to set everything up and get the following error:
`  Version:           GNU MP 6.1.0
  Host type:         none-pc-linux-gnu
  ABI:               standard
  Install prefix:    /usr/local/ps3dev/ppu
  Compiler:          gcc
  Static libraries:  yes
  Shared libraries:  no

make[1]: Leaving directory '/mnt/c/Users/nando/ps3toolchain/build/gcc-7.2.0/build-ppu'
make: *** [Makefile:898: all] Error 2
../scripts/002-gcc-newlib-PPU.sh: Failed.
ERROR: Could not run the toolchain script.`

I am unsure how to fix this, especially because I've got this working before a few months on the exact same system. Does anyone know what to do?

**Comment by zeldin** [comment]
Hard to say since the error message of the actual gcc build failure is not included in the snippet you pasted (it's probably a lot further up in the log due to the build being parallel).  Maybe you could pastebin the whole thing?

**Comment by nandolawson** [comment]
I've seem to fixed the error. I've used toolchain-sudo.sh before. After using toolchain.sh, it seems to work pretty well.
I can't see why toolchain-sudo.sh shouldn't work, which makes me wondering what was wrong with it.
