### ISSUE TITLE
 error: PIC register clobbered by 'r2' in 'asm'    asm volatile

### ISSUE THREAD

**Issue by crystalct** [ps3dev/ps3toolchain#86]
With gcc 7.2 all projects that useasm volatile can't be compiled any more.

Is there a work around?

**Comment by zeldin** [comment]
From the issue title it sounds like some very specific asm volatile is causing the issue.  Why does the code clobber r2?  Does it need to be PIC?

**Comment by crystalct** [comment]
It seems a bad idea to use PIC register clobbered...  and starting from gcc 7 it's not permiited any more....
