### ISSUE TITLE
Library problems with gcc 7.2.0 without -flto -ffat-lto-objects CFLAGS

### ISSUE THREAD

**Issue by crystalct** [ps3dev/ps3toolchain#87]
libcairo.a and libpixman-1.a doesn't work. Probably many others libs.

**Comment by miigotu** [comment]
Make a PR? ;)

**Comment by crystalct** [comment]
What's a PR?

**Comment by miigotu** [comment]
A pull request

**Comment by bucanero** [comment]
@crystalct btw, you updated the `cairo` and `pixman` libs, right? if you can, submit the scripts to the ps3libraries repo; I think it's nice to have updated versions. 😄

**Comment by zeldin** [comment]
I fixed the cairo issue by removing `-flto`.  (Upstreams cairo 1.14 and newer already have this fix, we might want to consider bumping to cairo 1.14.12 at some point.)

What was the issue with libpixman?
