### ISSUE TITLE
Failed to build latest docker container

### ISSUE THREAD

**Issue by dee12452** [ps3dev/ps3toolchain#95]
Hi!

Trying to get the latest toolchain in a docker container. I was using `https://hub.docker.com/r/psl1ght/psl1ght/tags`
but it seems the latest is really outdated.

I'm trying to build a new container locally with `docker build -t ps3toolchain-image .` and am getting the following

```
effect_position.c:33:10: fatal error: SDL.h: No such file or directory
 #include "SDL.h"
          ^~~~~~~
compilation terminated.
make: *** [build/effect_position.lo] Error 1
Makefile:137: recipe for target 'build/effect_position.lo' failed
scripts/005_SDL2_mixer-2.0.4.sh: Failed.
../scripts/014-sdl_psl1ght_libs.sh: Failed.
../scripts/009-ps3libraries.sh: Failed.
The command '/bin/sh -c /build/toolchain.sh' returned a non-zero code: 1
```

**Comment by nazarpechka** [comment]
The same problem when building on macOS, it would be fixed if we could change #include "SDL.h" to #include "SDL/SDL.h" in source code, but on each run of the scripts its redownloaded.

**Comment by zeldin** [comment]
Removed `005_SDL2_mixer-2.0.4.sh` for now.
