### ISSUE TITLE
stdatomic.h error

### ISSUE THREAD

**Issue by crystalct** [ps3dev/ps3toolchain#97]
/usr/local/ps3dev/ppu/lib/gcc/powerpc64-ps3-elf/7.2.0/include/stdatomic.h:63:17: error: unknown type name '__INT_FAST8_TYPE__'
 typedef _Atomic __INT_FAST8_TYPE__ atomic_int_fast8_t;
/usr/local/ps3dev/ppu/lib/gcc/powerpc64-ps3-elf/7.2.0/include/stdatomic.h:57:17: error: unknown type name '__INT_LEAST8_TYPE__'
 typedef _Atomic __INT_LEAST8_TYPE__ atomic_int_least8_t;

calling:
```
crystal@DESKTOP-2FII39V /usr/local/ps3dev
$ gcc -dM -E -x c /dev/null | grep __UINT_LEAST8_TYPE__
#define __UINT_LEAST8_TYPE__ unsigned char
```
calling:
```
crystal@DESKTOP-2FII39V /usr/local/ps3dev
$ ppu-gcc -dM -E -x c /dev/null | grep INT_LEAST8_TYPE

crystal@DESKTOP-2FII39V /usr/local/ps3dev
$ 

```

Is it correct?

**Comment by zeldin** [comment]
We probably need to add `newlib-stdint.h` to `tm_file`, like it is done for `powerpc-*-elf*`.

**Comment by zeldin** [comment]
The SPU toolchain already has `newlib-stdint.h` in its `tm_file`, and there it looks ok:

```
hakua:/tmp/ps3toolchain% echo "" | spu-gcc -dD -E -x c - | grep INT_LEAST8_TYPE
#define __INT_LEAST8_TYPE__ signed char
#define __UINT_LEAST8_TYPE__ unsigned char
hakua:/tmp/ps3toolchain% 
```

**Comment by zeldin** [comment]
There we go:
```
hakua:~% echo "" | ppu-gcc -dD -E -x c - | grep INT_LEAST8_TYPE
#define __INT_LEAST8_TYPE__ signed char
#define __UINT_LEAST8_TYPE__ unsigned char
hakua:~% 
```
@crystalct Please try again with latest toolchain now.  (Just rerunning `./toolchain.sh 002` is fine.)

**Comment by crystalct** [comment]
Great! I'll try.
