### ISSUE TITLE
NoRSX fails to build

### ISSUE THREAD

**Issue by mohasi** [ps3dev/ps3toolchain#99]
I am trying to build the `ps3toolchain` there was another issue https://github.com/ps3dev/PSL1GHT/issues/106 which blocks building but I was able to bypass that by using an older version of the `psl1ght` repo prior to that commit. So, now the build process almost reaches the end and then gives me this:

![image](https://user-images.githubusercontent.com/47725053/87237624-7cb49c00-c3f0-11ea-803b-011e8c3b93b4.png)

I think its referring to this struct, which I found in `usr/local/ps3dev/ppu/include/sys/spu.h`:
![image](https://user-images.githubusercontent.com/47725053/87237863-3e6cac00-c3f3-11ea-9453-48bef75501ab.png)

It is hard to figure out who is actually responsible for this, since its in @wargio repo, which is build by the `ps3libraries` repo which is built as part of this repo, so I am not sure. I think its best here since this is where others may find the same issue.

~~May I suggest that by linking to the latest versions of dozens of repos, pulling them and trying to build them is a recipe for disaster!~~ It seems that that the file in question has not been updated in years, so not sure how this is happening now.

**Comment by shagkur** [comment]
Hi,
Well directly responsible, as you correctly figured is wargio, but
indirectly it‘s me. Since i introduced those API changes. I‘ll fix it in
NoRSX.

Mohammed Asif <notifications@github.com> schrieb am So. 12. Juli 2020 um
04:40:

**Comment by wargio** [comment]
@shagkur when these changes were introduced?

**Comment by wargio** [comment]
Merged. this should fix the issue. please try to reinstall the libs again.

**Comment by shagkur** [comment]
The commit i made is ~2 days ago. Its along with alot of other additions
and improvements to psl1ght.

Giovanni <notifications@github.com> schrieb am So. 12. Juli 2020 um 21:27:

**Comment by wargio** [comment]
ok. i see.

**Comment by mohasi** [comment]
Thanks @shagkur for fix and @wargio for merge. I can confirm the build is now working again.
